version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/backend:rw"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "1234:1234"
      - "42821:42821"
    volumes:
      - "./frontend:/frontend:rw"
      - /frontend/node_modules
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80
      - 443:443