version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/backend:rw"
    
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${db}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1234:1234"
      - "42821:42821"
    volumes:
      - "./frontend:/frontend:rw"
      - /frontend/node_modules

  nginx:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"